name: Update Events

on:
  repository_dispatch:
    types: [update-events]

jobs:
  update-events:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Update events.json
        run: |
          echo '${{ github.event.client_payload.events }}' > events.json
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add events.json
          git diff --staged --quiet || git commit -m "Update events from calendar app"
          git push
